---
name: "⛔️ Update dependencies"

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * FRI"

jobs:
  update-dependencies:
    name: "Update Python modules"
    runs-on: ubuntu-latest
    permissions:
      # IMPORTANT: mandatory to raise the PR
      id-token: write
      pull-requests: write
      repository-projects: write
      contents: write

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: "Set up Python ${{ matrix.python-version }}"
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: "Setup PDM for build commands"
        uses: pdm-project/setup-pdm@v3

      - name: "Install dependencies"
        run: |
          python -m pip install --upgrade pip
          pdm lock
          pdm export -o requirements.txt
          # Add banner reminder to NOT edit requirements.txt file
          mv requirements.txt /tmp/requirements.txt
          cp .requirements-banner.txt requirements.txt
          cat /tmp/requirements.txt >> requirements.txt

      - name: Update dependencies
        uses: ModeSevenIndustrialSolutions/update-deps-action@v1
        with:
          sign-off-commit: "true"
          token: ${{ secrets.GH_TOKEN }}
          commit-message: "Chore: Update dependencies and pdm.lock"
          pr-title: "Update Python module dependencies"
          update-strategy: eager
          # Whether to install PDM plugins before update
          install-plugins: "false"
